const courses = [
  {
    id: 1,
    title: "C Programming",
    slug: "c-programming",
    img: "/courseImages/c.jpg",
    duration: "2 Months",
    level: "Beginner",
  },
  {
    id: 2,
    title: "C++ Programming",
    slug: "cpp-programming",
    img: "/courseImages/c++.jpg",
    duration: "3 Months",
    level: "Beginner to Intermediate",
  },
  {
    id: 3,
    title: "Python Programming",
    slug: "python-programming",
    img: "/courseImages/python1.jpg",
    duration: "3 Months",
    level: "Beginner to Advanced",
  },
  {
    id: 4,
    title: "Web Development",
    slug: "web-development",
    img: "/courseImages/webdevlopment.",
    duration: "6 Months",
    level: "Full Stack",
  },
  {
    id: 5,
    title: "Data Structures",
    slug: "data-structures",
    img: "/courseImages/DS.jpg",
    duration: "4 Months",
    level: "Intermediate",
  },
  {
    id: 6,
    title: "Advanced Excel",
    slug: "excel",
    img: "/courseImages/excel.jpg",
    duration: "1 Month",
    level: "Beginner",
  },
  {
    id: 7,
    title: "PHP Development",
    slug: "php-development",
    img: "/courseImages/php.jpg",
    duration: "3 Months",
    level: "Beginner to Intermediate",
  },
  {
    id: 8,
    title: "Java Programming",
    slug: "java-programming",
    img: "/courseImages/java.jpg",
    duration: "4 Months",
    level: "Beginner to Advanced",
  },
  {
    id: 9,
    title: ".NET Development",
    slug: "dotnet-development",
    img: "/courseImages/.net.jpg",
    duration: "4 Months",
    level: "Intermediate",
  },
  {
    id: 10,
    title: "SQL & Databases",
    slug: "sql-database",
    img: "/courseImages/sql.jpg",
    duration: "2 Months",
    level: "Beginner",
  },
];

export default coursesConfig;
